### ISSUE TITLE
Generate documentation on how to execute mint cli locally (with a model)

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#14]
By March 30th we need to generate documentation on how to install and test models from your laptop using mint cli.  We can use HAND as a test case and TopoFlow as an advanced setup.

The tutorial should explain how to install everything with Singularity and configure it so we can run it locally.

**Comment by mosoriob** [comment]
Please, review it https://dame-cli.readthedocs.io/en/latest/

**Comment by dgarijo** [comment]
I will review and close the issue.

**Comment by dgarijo** [comment]
I was able to install the CLI, but I don't have singularity so I haven't tested the full execution.

**Comment by dgarijo** [comment]
I have also reviewed and commited changes to the doc. Please redo the readthedocs if it's not set up automatically.
