### ISSUE TITLE
When an input is requested, it is not clear what is expected.

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#20]
**Describe the bug**
Reported by @varunratnakar :

> Running with the example configuration in Usage notes  ( modflow )
> - It asks "Please, enter the url of the previous input:". It wasn't very clear what this previous input is. 

**Action**
Clarify the description of the requested inputs

**Comment by mosoriob** [comment]
How?

**Comment by dgarijo** [comment]
I think we can change the sentence to be:

"This model configuration requires an input that has not been specified. Please, enter the URL of the input described in the table above"

**Comment by varunratnakar** [comment]
The table looks like the following:

**Comment by varunratnakar** [comment]
The table looks like the following:

```
+--------------------+----------------------------------------------+
|      Property      |                    Value                     |
+====================+==============================================+
| has_dimensionality | [0]                                          |
+--------------------+----------------------------------------------+
| has_format         | ['hf6']                                      |
+--------------------+----------------------------------------------+
| description        | ['Horizontal flow barrier file']             |
+--------------------+----------------------------------------------+
| position           | [8]                                          |
+--------------------+----------------------------------------------+
| id                 | https://w3id.org/okn/i/mint/modflow_2005_Hfb |
+--------------------+----------------------------------------------+
| label              | ['hfb6']                                     |
+--------------------+----------------------------------------------+
Please, enter the url of the previous input: 
```
Looking at the table, I don't know what "previous input" refers to. What kind of data is it ? Also, please provide an example URL to the data to try out.

Edit.. Oh.. I see by previous input, you mean the above input !! Yes please change the sentence.. The word previous is misleading. Maybe state on top something like. To run this model conifguration, a 'Horizontal flow barrier file' (.hf6 file) is required. Please enter a url for it. Not sure if we need all that extra information about position, id, dimensionality
