### ISSUE TITLE
Allow overwriting a certain parameter value

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#21]
Right now we take all default values from the model config/setup. However, users may want to test potential setups that have not been declared yet. We should allow a new way of running dame that allows selecting and overwriting parameters.

This adds more complexity to the original design.

**Comment by brandomr** [comment]
Curious if there is any update on this issue? I noticed some recent commits that look like this may have been implemented?

**Comment by dgarijo** [comment]
Yes, @sirspock addressed this issue. @sirspock can we close this? (I know it's solved; I don't know if the changes have been merged on the main branch)

**Comment by mosoriob** [comment]
I released a new version of DAME with the feature.

https://github.com/mintproject/dame_cli/releases/tag/5.2.0

**Comment by brandomr** [comment]
Awesome. @sirspock is there documentation on how to use this feature?

**Comment by dgarijo** [comment]
@brandomr when you run dame, now you will see:
```
The information needed to run the model is complete, and I can execute the model as follows:
Do you want to edit the parameters? [y/N]:
```
If you choose y, then you will be able to overwrite parameters

Example:
```
(.venv)  node1 ~ dame run cycles-0.10.2-alpha-collection-oromia-single-point
Information about the model configuration
Inputs
- cycles_weather_soil: https://data.mint.isi.edu/files/cycles-input-data/oromia/weather-soil/Arsi_Amigna_7.884865046N_40.19527054E.zip
- cycles_crops: https://raw.githubusercontent.com/pegasus-isi/pegasus-cycles/master/data/crops.crop
Parameters
- start_planting_day: 100
- end_year: 2017
- fertilizer_rate: 0
- crop_name: Maize
- end_planting_day: 149
- use_forcing: FALSE
- weed_fraction: 0.05
- start_year: 2000
Docker Image
- Name: mintproject/cycles:0.10.2-alpha - https://hub.docker.com/r/mintproject/cycles
Component Location
- Link: https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/cycles-0.10.2-alpha-collection/cycles-0.10.2-alpha-collection.zip
The information needed to run the model is complete, and I can execute the model as follows:
Do you want to edit the parameters? [y/N]: y
- start_planting_day: 100
Enter the new value [100]:
....
```

**Comment by dgarijo** [comment]
@brandomr we will this to the documentation soon; but I hope this is enough for you to play around?

**Comment by mosoriob** [comment]
I would like to save the new scenario as a ModelConfigurationSetup

**Comment by dgarijo** [comment]
Maybe that's something that we can ask users, because they may be trying stuff that it's not worth saving.

**Comment by brandomr** [comment]
@dgarijo that should work and seems pretty straightforward to me. Thanks!
