### ISSUE TITLE
Error executing DAME in mac

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#27]
Rajiv installed DAME on his mac and typed:
```
 (venv)  ✓ mayani@Mayani-MacBook-Pro   /tmp/x  🐍 global:vscode  dame run cycles-0.10.2-alpha-collection-oromia-single-point                                                                
The information of the setup is complete
Executing the setup
2020-04-16 20:16:49,979 root         INFO     Execution cycles-0.10.2-alpha-collection-oromia-single-point running,  check the logs on executions/cycles-0.10.2-alpha-collection-oromia-single-point_defcb382-8059-11ea-ac25-acde48001122/output.log
/.singularity.d/actions/exec: line 9: /Users/mayani/run: No such file or directory
[    1.308773] reboot: Power down
[cycles-0.10.2-alpha-collection-oromia-single-point] The execution has been successful
[cycles-0.10.2-alpha-collection-oromia-single-point] Results available at: executions/cycles-0.10.2-alpha-collection-oromia-single-point_defcb382-8059-11ea-ac25-acde48001122/cycles-0.10.2-alpha-collection/src 
(venv)  ✓ mayani@Mayani-MacBook-Pro   /tmp/x  🐍 global:vscode  ls executions/cycles-0.10.2-alpha-collection-oromia-single-point_defcb382-8059-11ea-ac25-acde48001122/cycles-0.10.2-alpha-collection/src
Arsi_Amigna_7.884865046N_40.19527054E.zip crops.crop                                io.sh                                     template-weed.operation                   template.operation
__pegasus-job.properties                  cycles-wrapper.py                         run                                       template.ctrl
```
I have not been able to reproduce the error on a linux server, and Rajiv neither. It may be mac-specific.

**Comment by mosoriob** [comment]
It works on my mac
@mayani can you retry it with the new version?

Can you give me the following information?
- Singularity version: `singularity version`
- Python version: `python -V`
- Dame version: `dame version`

```
dame run cycles-0.10.2-alpha-collection-oromia-single-point                                      took 11s Py dame-prod
The information of the setup is complete
Executing the setup
2020-04-17 10:06:59,351 root         INFO     Execution cycles-0.10.2-alpha-collection-oromia-single-point running,  check the logs on executions/cycles-0.10.2-alpha-collection-oromia-single-point_d8575716-80cd-11ea-b220-faffc21691f4/output.log

...
[   25.296954] reboot: Power down
[cycles-0.10.2-alpha-collection-oromia-single-point] The execution has been successful
[cycles-0.10.2-alpha-collection-oromia-single-point] Results available at: executions/cycles-0.10.2-alpha-collection-oromia-single-point_d8575716-80cd-11ea-b220-faffc21691f4/cycles-0.10.2-alpha-collection/src
```

**Comment by mayani** [comment]
I continue to get the same error.

Singularity Version: 3.3.0-rc.1.658.g7427b73f1.dirty
Python: 3.7.6
DAME: v3.4.1

**Comment by mosoriob** [comment]
Wow, we are using the same environment.

~ ❯ python -V
Python 3.7.6
~ ❯ dame version
DAME: v3.4.1
~ ❯ /usr/local/bin/singularity version
3.3.0-rc.1.658.g7427b73f1.dirty

**Comment by dgarijo** [comment]
Do you both have a virtual environment? Maybe the dependencies on each of you are different

**Comment by mayani** [comment]
Package            Version   
------------------ ----------
attrs              19.3.0    
certifi            2020.4.5.1
chardet            3.0.4     
click              7.1.1     
dame-cli           3.4.1     
decorator          4.4.2     
idna               2.9       
importlib-metadata 1.6.0     
ingestion-api      1.3.4     
jsonschema         3.2.0     
modelcatalog-api   2.4.0     
pip                20.0.2    
pyrsistent         0.16.0    
python-dateutil    2.8.1     
PyYAML             5.3.1     
requests           2.23.0    
semver             2.9.1     
setuptools         45.2.0    
six                1.14.0    
texttable          1.6.2     
urllib3            1.25.9    
validators         0.14.3    
wheel              0.34.2    
zipp               3.1.0

**Comment by mosoriob** [comment]
We found more issues with Singularity and macOS. We're going to drop the support.
