### ISSUE TITLE
DAME and DataTransformation

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#41]
@sirspock, this will add new dependencies in the model catalog and will need to be discussed in detail. This new functionality implies the execution of data transformation  and postprocessing steps for a model. 

Assuming this information is available in the knowledge base, DAME will be able to invoke the transformation pipeline (dockerized) to produce inputs to be used by the model. Initially this will be done in 2 steps: the user activates the transformation giving the original input; and then executes the model with DAME.

- [x] Test the pull request Minh
- [x] Add Data Transformation resource to the Model Catalog [issue](https://github.com/mintproject/ModelCatalog/issues/47)
- [x] Fix v1.5.0 tests [issue](https://github.com/mintproject/model-catalog-api/issues/120)
    - [x] After, release v1.5.0 server 
    - [x] Update the model catalog client python
- [x] Test: mic and dame using model catalog client 1.5.0
    - [x] Release the model catalog client python
- [ ] ~Search dataset-id using the DataCatalog python client~
- [x] Overwrite the parameters

**Comment by mosoriob** [comment]
We need to talk with the other team. They haven't share any plan of the architecture with me. 
Do you have any information?

Without a plan, this is going to fail and DAME cannot fix it.

**Comment by dgarijo** [comment]
I do not have additional information, and I think you are right. We should engage with them soon or this feature will not be ready.
What I know is that they will provide a container with the transformations.

**Comment by dgarijo** [comment]
Conversation started. They have: https://github.com/mintproject/MINT-Transformation for declaring their containers. Please let me know if you don't have access.

**Comment by mosoriob** [comment]
The first version of this issue has been addressed.
