### ISSUE TITLE
DAME-DAKOTA integration

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#42]
This issue needs to be discussed, @sirspock.

The context is that if a model needs to be calibrated, DAME should provide the means to do so through DAKOTA. It is unclear to me at the moment how this workflow for this will be, because DAME was designed as a testing tool. Maybe this is to start testing the calibration of a model and show how to set it up.

**Comment by dgarijo** [comment]
According to Yolanda, this is not a priority right now. Therefore I will remove it from end of May release

**Comment by mosoriob** [comment]
inactive.
