### ISSUE TITLE
Documentation - Milestone end of APRIL

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#51]
We have updated documentation for DAME 4.1.3, but we should update it for the release that cover all items of this milestone:
- How to list setups and configurations
- How to overwrite things
- How to load local paths

**Comment by dgarijo** [comment]
New documentation covers:
- [x] How to list configurations and setups
- [x] How to load local paths

**Comment by mosoriob** [comment]
I'm going to close this issue. Seems old.
