### ISSUE TITLE
Documentation - End of May

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#52]
This issue is to update the documentation with the end of may release.

**Comment by mosoriob** [comment]
Updates?

**Comment by dgarijo** [comment]
Can we rename it to end of June?
We did some minor updates in May, but we have spent most of our effort in MIC

**Comment by mosoriob** [comment]
Updates?

**Comment by dgarijo** [comment]
I didn't have time to add the doc about the parameter values that can be changed now. If you have the time, then please add it.

For the data transformations doc I think I need some examples available first.

**Comment by dgarijo** [comment]
Closing because there is an issue for doc in June
