### ISSUE TITLE
dame credentials not working for other instances of mint

### ISSUE THREAD

**Issue by iperezx** [mintproject/dame_cli#87]
**Describe the bug**
I can't configure dame to change change to a different mint instance (server). Specifically: https://api.models.wildfire.mint.isi.edu/v1.7.0

Setup:
Running on macOS:
   System Version: macOS 11.2.1 (20D74)
      Kernel Version: Darwin 20.3.0

DAME: v5.6.0

pip install
pip version: pip 20.3.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

**To Reproduce**
- dame credentials --server https://api.models.wildfire.mint.isi.edu/v1.7.0 --username mint@isi.edu
-  dame browse 
-  it should then take me to https://wifire.models.mint.isi.edu/home 

OR
-  dame credentials
- input the same information as above for server and username
- dame browse
- go to https://wifire.models.mint.isi.edu/home

OR (not sure how the profile is being used when using dame browse)
- dame credentials -p wifire --server https://api.models.wildfire.mint.isi.edu/v1.7.0 --username mint@isi.edu
- dame browse

**Expected behavior**
I should be able to configure dame to use a different instance of mint and use dame browse. I have not tested with any other dame commands (dame run  etc.)  after setting my dame credentials with https://api.models.wildfire.mint.isi.edu/v1.7.0.

Comments:
-  This test does not cover other mint instances since the param passed in for server is the same in the config file you are loading in: https://github.com/mintproject/dame_cli/blob/master/src/dame/tests/test_cli_methods.py#L19

**Comment by iperezx** [comment]
I also tried it with `dame run 5630a04c-ef7c-436e-8ac4-9210da7c4eec` for one of the resources in this model: https://wifire.models.mint.isi.edu/models/explore/quic_fire/079abcb9-4277-4800-8a70-966947a83f1c/dee50e48-091f-471d-ae41-5dde3f467891/5630a04c-ef7c-436e-8ac4-9210da7c4eec

**Comment by mosoriob** [comment]
Thanks for the issue. 
Please upgrade to the version


```bash
pip install dame-cli==5.6.1
```
